# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Fix issue with vbguest plugin v0.21.0+ 
  # https://github.com/dotless-de/vagrant-vbguest/issues/399
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # Virtual Box and VM resource allocation
  # Note: These are provider-specific configurations
  config.vm.provider "virtualbox" do |vb|
    vb.name = "CentOS7_K3s_Dev"
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    # Customize the amount of vCPUs on the VM: 
    vb.cpus = 4
  end

  # Networking
  config.vm.hostname = "k3s-dev.local"
  config.vm.network :private_network, ip: "192.168.33.10"
  # Uncomment this to forward VM ports and get access via localhost:8080
  # Run command to actualize changes `vagrant reload`
  # config.vm.network :forwarded_port, guest: 8080, host:8080

  # Synced folders
  # Sync the /src folder from the host machine
  config.vm.synced_folder "src/", "/home/vagrant/src"
 
  # Shell provisioner
  # https://www.vagrantup.com/docs/provisioning/shell
  # Runs `bootstrap.sh` as root, update available packages and install K3s
  config.vm.provision "bootstrap", type: "shell", path: "scripts/bootstrap.sh"
  # Runs `extras.sh` as the default user `vagrant`, install further dev tools after bootstrap
  config.vm.provision "extras", after: "bootstrap", type: "shell", privileged: false, path: "scripts/extras.sh"

end
