# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Fix issue with vbguest plugin v0.21.0+ 
  # https://github.com/dotless-de/vagrant-vbguest/issues/399
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
    vb.name = "CentOS7_K3s_Dev"
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    # Customize the amount of vCPUs on the VM: 
    vb.cpus = 4
   end
 
  # Shell provisioner
  # https://www.vagrantup.com/docs/provisioning/shell
  config.vm.provision "bootstrap", type: "shell", inline:<<-SHELL    
    yum update -y
    # Standard dev tools
    yum install -y git
    # Install K3s using install script. 
    # See more: https://rancher.com/docs/k3s/latest/en/quick-start/
    export K3S_KUBECONFIG_MODE="644"
    export INSTALL_K3S_EXEC="--node-name k3s-dev-node"
    curl -sfL https://get.k3s.io | sh -
    SHELL

  # Sync a folder on the host machine to the guest machine  
  config.vm.synced_folder "src/", "/home/vagrant/src"
end
